spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
          access-key: LTAI4GEuyK9sLhTNa2caD6fF
          secret-key: ghY9rfzt2daUwPljF8vowXVwXcr8TD
          oss:
            endpoint: oss-cn-beijing.aliyuncs.com
            bucket: qkj-gulimall
  application:
    name: gulimall-third-party


server:
  port: 13000
logging:
  level:
    com.atguigu.gulimall: debug